title: Strategy ToolBox
description: Boite à outils pour les stratégies de nos robots

# Theme
remote_theme: leskaribous/JustTheDocsTemplate

# Plugins

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-pdf-embed

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby